### ISSUE TITLE
Confusing examples.

### ISSUE THREAD

**Issue by mrdoob** [pnitsch/BitmapData.js#2]
The bycicles examples use a (resized) 512x340 image, while the BitmapData gets inited at 300x300. The result of this is that post processed images don't match up. Gives the impression that by applying a filter to the image it's also cropping it. At first it I thought it was something wrong with the code, but then I realised it was a much simpler issue...

**Comment by pnitsch** [comment]
that's a good point. it's not clear enough. 

the cropping was intentional since that's how flash would handle a draw operation on a brand new BitmapData object. the alternative was adding the 'bitmapData' property to the Image object which draws the data at the accurate dimensions. 

i will take a step back and take a better look at how usable the api is. it might require some reorganization. for instance, it might be good to add an .image property that returns an Image object (from toDataUrl) for easier management on a stage.

**Comment by mrdoob** [comment]
Uh. I don't think the API is confusing. I think it's doing what you would expect.

What it's confusing for a noob looking at the lib is the fact that the examples are using a 512x340 image, and then the <img> is resized to 300x300.

It'll be simpler to just use a 300x300 image to begin with, or to remove the resizing and create BitmapDatas of 512x340...
